from typing import Union
from pydantic import BaseModel
from datetime import datetime

class Record(BaseModel):
    REF_DATE: datetime
    TARGET: int
    VAR2: Union[str, None]
    IDADE: Union[float, None]
    VAR5: Union[str, None]
    VAR6: Union[float, None]
    VAR7: Union[float, None]
    VAR8: Union[str, None]
    VAR9: Union[str, None]
    VAR10: Union[str, None]
    VAR11: Union[float, None]
    VAR12: Union[float, None]
    VAR14: Union[float, None]
    VAR15: Union[float, None]
    VAR16: Union[float, None]
    VAR18: Union[float, None]
    VAR19: Union[float, None]
    VAR22: Union[float, None]
    VAR24: Union[float, None]
    VAR25: Union[float, None]
    VAR32: Union[str, None]
    VAR39: Union[float, None]
    VAR40: Union[float, None]
    VAR41: Union[float, None]
    VAR42: Union[float, None]
    VAR47: Union[float, None]
    VAR49: Union[str, None]
    VAR50: Union[str, None]
    VAR51: Union[str, None]
    VAR52: Union[str, None]
    VAR53: Union[str, None]
    VAR54: Union[str, None]
    VAR55: Union[str, None]
    VAR56: Union[str, None]
    VAR57: Union[str, None]
    VAR58: Union[str, None]
    VAR59: Union[str, None]
    VAR60: Union[str, None]
    VAR61: Union[str, None]
    VAR62: Union[str, None]
    VAR63: Union[str, None]
    VAR64: Union[str, None]
    VAR65: Union[str, None]
    VAR66: Union[str, None]
    VAR67: Union[str, None]
    VAR68: Union[str, None]
    VAR69: Union[str, None]
    VAR70: Union[str, None]
    VAR71: Union[str, None]
    VAR72: Union[str, None]
    VAR73: Union[str, None]
    VAR74: Union[str, None]
    VAR75: Union[str, None]
    VAR76: Union[str, None]
    VAR77: Union[str, None]
    VAR78: Union[str, None]
    VAR79: Union[str, None]
    VAR80: Union[str, None]
    VAR81: Union[str, None]
    VAR82: Union[str, None]
    VAR83: Union[str, None]
    VAR84: Union[str, None]
    VAR85: Union[str, None]
    VAR86: Union[str, None]
    VAR87: Union[str, None]
    VAR88: Union[str, None]
    VAR89: Union[str, None]
    VAR90: Union[str, None]
    VAR91: Union[str, None]
    VAR92: Union[str, None]
    VAR93: Union[str, None]
    VAR94: Union[str, None]
    VAR95: Union[str, None]
    VAR96: Union[str, None]
    VAR97: Union[str, None]
    VAR98: Union[str, None]
    VAR99: Union[str, None]
    VAR100: Union[str, None]
    VAR101: Union[str, None]
    VAR102: Union[str, None]
    VAR103: Union[str, None]
    VAR104: Union[str, None]
    VAR105: Union[str, None]
    VAR106: Union[str, None]
    VAR107: Union[str, None]
    VAR108: Union[str, None]
    VAR109: Union[str, None]
    VAR110: Union[str, None]
    VAR111: Union[str, None]
    VAR112: Union[str, None]
    VAR113: Union[str, None]
    VAR114: Union[str, None]
    VAR115: Union[str, None]
    VAR116: Union[str, None]
    VAR117: Union[str, None]
    VAR118: Union[str, None]
    VAR119: Union[str, None]
    VAR120: Union[str, None]
    VAR121: Union[str, None]
    VAR122: Union[str, None]
    VAR123: Union[str, None]
    VAR124: Union[str, None]
    VAR125: Union[str, None]
    VAR126: Union[str, None]
    VAR127: Union[str, None]
    VAR128: Union[str, None]
    VAR129: Union[str, None]
    VAR130: Union[str, None]
    VAR131: Union[str, None]
    VAR132: Union[str, None]
    VAR133: Union[str, None]
    VAR134: Union[str, None]
    VAR135: Union[str, None]
    VAR136: Union[str, None]
    VAR137: Union[str, None]
    VAR138: Union[str, None]
    VAR139: Union[str, None]
    VAR140: Union[str, None]
    VAR141: Union[float, None]
    VAR142: Union[str, None]

class Prediction(BaseModel):
    mes: int
    volumetria: int
    performance: float

class Path(BaseModel):
    path: str

class Adherence(BaseModel):
    statistic: float
    p_value: float
